import Head from 'next/head'
import {gql, useQuery} from '@apollo/client'
import {getApolloClient} from "../apollo";
import {GetStaticProps, NextComponentType} from "next";

const message = gql`
    query {
        categories {
            name,
            id
        }
    }
`

const Home: NextComponentType = (props) => {

    const {data, loading} = useQuery(message)
    console.log(data)

    return (
        <div>
            <Head>
                <title>Blog</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main>
                {!loading && data.categories.map(it => <p key={it.name}>{it.name}</p>)}
            </main>
        </div>
    )
}

export const getStaticProps: GetStaticProps = async () => {
    const client = getApolloClient()
    await client.query({
        query: message
    })
    return {
        props: {
            apolloState: client.cache.extract()
        }

    }
}

export default Home
